[package]
name = "tuna"
version = "0.1.0"
authors = ["Matthew D. Steele <mdsteele@alum.mit.edu>"]
license = "GPL-3.0+"
build = "build.rs"

[dependencies]
ahi = { git = "https://github.com/mdsteele/ahi" }

[dependencies.sdl2]
version = "0.31"
features = ["unsafe_textures", "use_mac_framework"]
